# Generated by Django 5.2.1 on 2026-09-04 10:01 (manually edited for safe slug migration)

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    """Populate slugs for all existing Scheme rows."""
    Scheme = apps.get_model('schemesapp', 'Scheme')
    seen = {}
    for scheme in Scheme.objects.all().order_by('id'):
        base = slugify(scheme.name) or f"scheme-{scheme.pk}"
        slug = base
        counter = 1
        while slug in seen:
            slug = f"{base}-{counter}"
            counter += 1
        seen[slug] = True
        scheme.slug = slug
        scheme.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('schemesapp', '0028_application_created_at_application_updated_at'),
    ]

    operations = [
        # Step 1: Add slug as nullable (no unique constraint yet)
        migrations.AddField(
            model_name='scheme',
            name='slug',
            field=models.SlugField(max_length=300, null=True, blank=True),
        ),
        # Step 2: Add timestamps
        migrations.AddField(
            model_name='scheme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        # Step 3: Populate slugs from existing names
        migrations.RunPython(generate_slugs, migrations.RunPython.noop),
        # Step 4: Now enforce unique + not-null
        migrations.AlterField(
            model_name='scheme',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
